name: oldmutual_pensions_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  envied: ^1.1.1
  equatable: ^2.0.7
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  pinput: ^5.0.1

dev_dependencies:
  build_runner: ^2.4.15 # build generated files
  envied_generator: ^1.1.1 # obfuscate credentials
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
