class Porting {
  String? nameOfCurrentEmployer;
  String? currentSchemeType;
  String? currentSchemeName;
  String? nameOfPrevEmployer;
  String? prevSchemeType;
  String? prevSchemeName;
  String? nameOfPrevTrustee;
  String? prevTrusteeContactName;
  String? prevTrusteeContactNumber;
  String? updatedAt;
  String? createdAt;
  int? id;
  int? userId;

  Porting({
    this.nameOfCurrentEmployer,
    this.currentSchemeType,
    this.currentSchemeName,
    this.nameOfPrevEmployer,
    this.prevSchemeType,
    this.prevSchemeName,
    this.nameOfPrevTrustee,
    this.prevTrusteeContactName,
    this.prevTrusteeContactNumber,
    this.updatedAt,
    this.createdAt,
    this.id,
    this.userId,
  });

  Porting.fromJson(Map<String, dynamic> json) {
    nameOfCurrentEmployer = json['name_of_current_employer'];
    currentSchemeType = json['current_scheme_type'];
    currentSchemeName = json['current_scheme_name'];
    nameOfPrevEmployer = json['name_of_prev_employer'];
    prevSchemeType = json['prev_scheme_type'];
    prevSchemeName = json['prev_scheme_name'];
    nameOfPrevTrustee = json['name_of_prev_trustee'];
    prevTrusteeContactName = json['prev_trustee_contact_name'];
    prevTrusteeContactNumber = json['prev_trustee_contact_number'];
    updatedAt = json['updated_at'];
    createdAt = json['created_at'];
    id = json['id'];
    userId = json['user_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['name_of_current_employer'] = nameOfCurrentEmployer;
    data['current_scheme_type'] = currentSchemeType;
    data['current_scheme_name'] = currentSchemeName;
    data['name_of_prev_employer'] = nameOfPrevEmployer;
    data['prev_scheme_type'] = prevSchemeType;
    data['prev_scheme_name'] = prevSchemeName;
    data['name_of_prev_trustee'] = nameOfPrevTrustee;
    data['prev_trustee_contact_name'] = prevTrusteeContactName;
    data['prev_trustee_contact_number'] = prevTrusteeContactNumber;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    data['user_id'] = userId;
    return data;
  }
}

class Autogenerated {
  bool? success;
  Data? data;
  String? message;

  Autogenerated({this.success, this.data, this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
    message = json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}

class Data {
  String? nameOfCurrentEmployer;
  String? currentSchemeType;
  String? currentSchemeName;
  String? nameOfPrevEmployer;
  String? prevSchemeType;
  String? prevSchemeName;
  String? nameOfPrevTrustee;
  String? prevTrusteeContactName;
  String? prevTrusteeContactNumber;
  String? updatedAt;
  String? createdAt;
  int? id;
  int? userId;

  Data({
    this.nameOfCurrentEmployer,
    this.currentSchemeType,
    this.currentSchemeName,
    this.nameOfPrevEmployer,
    this.prevSchemeType,
    this.prevSchemeName,
    this.nameOfPrevTrustee,
    this.prevTrusteeContactName,
    this.prevTrusteeContactNumber,
    this.updatedAt,
    this.createdAt,
    this.id,
    this.userId,
  });

  Data.fromJson(Map<String, dynamic> json) {
    nameOfCurrentEmployer = json['name_of_current_employer'];
    currentSchemeType = json['current_scheme_type'];
    currentSchemeName = json['current_scheme_name'];
    nameOfPrevEmployer = json['name_of_prev_employer'];
    prevSchemeType = json['prev_scheme_type'];
    prevSchemeName = json['prev_scheme_name'];
    nameOfPrevTrustee = json['name_of_prev_trustee'];
    prevTrusteeContactName = json['prev_trustee_contact_name'];
    prevTrusteeContactNumber = json['prev_trustee_contact_number'];
    updatedAt = json['updated_at'];
    createdAt = json['created_at'];
    id = json['id'];
    userId = json['user_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['name_of_current_employer'] = nameOfCurrentEmployer;
    data['current_scheme_type'] = currentSchemeType;
    data['current_scheme_name'] = currentSchemeName;
    data['name_of_prev_employer'] = nameOfPrevEmployer;
    data['prev_scheme_type'] = prevSchemeType;
    data['prev_scheme_name'] = prevSchemeName;
    data['name_of_prev_trustee'] = nameOfPrevTrustee;
    data['prev_trustee_contact_name'] = prevTrusteeContactName;
    data['prev_trustee_contact_number'] = prevTrusteeContactNumber;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    data['user_id'] = userId;
    return data;
  }
}
